apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: full
            widgets:
              - type: header
                title: Homelab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  labels: { app: glance }
spec:
  replicas: 1
  selector: { matchLabels: { app: glance } }
  template:
    metadata: { labels: { app: glance } }
    spec:
      nodeSelector: { role: apps }
      containers:
        - name: glance
          image: glanceapp/glance:latest
          ports: [{ containerPort: 8080 }]
          volumeMounts:
            - name: cfg
              mountPath: /app/config        # mount the whole dir
              readOnly: true
      volumes:
        - name: cfg
          configMap:
            name: glance-config
            items:
              - key: glance.yml
                path: glance.yml
---
apiVersion: v1
kind: Service
metadata:
  name: glance
spec:
  type: NodePort
  selector: { app: glance }
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
